defaults: &defaults
  adapter: postgresql
  username: rails
  password: r00t
  encoding: utf8
  template: template0
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: guia041_development

#test:
#  <<: *defaults
#  database: guia041_test

#production:
#  <<: *defaults
#  database: guia041_production
