# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Category.delete_all
# Neighborhood.delete_all
# City.delete_all
# Place.delete_all

# Category.create(title: "Academias e Esportes")
# Category.create(title: "Alimentos e Bebidas")
# Category.create(title: "Animais e Pet Shop")
# Category.create(title: "Audio, Video e Foto")
# Category.create(title: "Autos e Acessórios")
# Category.create(title: "Bares")
# Category.create(title: "Casa e Decoração")
# Category.create(title: "Construção Civil")
# Category.create(title: "Consultores e Profissionais")
# Category.create(title: "Educação e Ensino")
# Category.create(title: "Eletro e Eletrônicos")
# Category.create(title: "Festas e Eventos")
# Category.create(title: "Restaurantes")
# Category.create(title: "Hotéis e Motéis")
# Category.create(title: "Imóveis e Empreendimentos")
# Category.create(title: "Informática e Internet")
# Category.create(title: "Livraria e Papelaria")
# Category.create(title: "Medicina e Saúde")
# Category.create(title: "Moda e Beleza")
# Category.create(title: "Presentes")
# Category.create(title: "Prestação de Serviços")
# Category.create(title: "Propaganda e Publicidade")
# Category.create(title: "Viagens e Turismo")

# Category.create(parent_id: 1	, title: "Academia para Mulheres")
# Category.create(parent_id: 1	, title: "Aparelhos de Ginástica")
# Category.create(parent_id: 1	, title: "Artes Marciais")
# Category.create(parent_id: 1	, title: "Artigos Esportivos")
# Category.create(parent_id: 1	, title: "Ballet - Jazz ")
# Category.create(parent_id: 1	, title: "Danças de Salão")
# Category.create(parent_id: 1	, title: "Defesa Pessoal")
# Category.create(parent_id: 1	, title: "Escola de Futebol")
# Category.create(parent_id: 1	, title: "Golf - Tênis - Squash")
# Category.create(parent_id: 1	, title: "Loja de Esporte")
# Category.create(parent_id: 1	, title: "Natação -  Hidro Ginástica")
# Category.create(parent_id: 1	, title: "Paintball")
# Category.create(parent_id: 1	, title: "Personal Training")
# Category.create(parent_id: 1	, title: "Pilates -  Yoga")
# Category.create(parent_id: 1	, title: "Tiroleza - Rapeú ")
# Category.create(parent_id: 2	, title: "Açougues")
# Category.create(parent_id: 2	, title: "Adegas")
# Category.create(parent_id: 2	, title: "Armazéns e Empórios")
# Category.create(parent_id: 2	, title: "Atacadistas")
# Category.create(parent_id: 2	, title: "Cachorros Quentes")
# Category.create(parent_id: 2	, title: "Cafés,Chás e Chocolates")
# Category.create(parent_id: 2	, title: "Casa de Carnes")
# Category.create(parent_id: 2	, title: "Chocolates")
# Category.create(parent_id: 2	, title: "Congelados")
# Category.create(parent_id: 2	, title: "Distribuidora de Alimentos")
# Category.create(parent_id: 2	, title: "Doces e Docerias")
# Category.create(parent_id: 2	, title: "Embalagens e descartáveis")
# Category.create(parent_id: 2	, title: "Esfihas")
# Category.create(parent_id: 2	, title: "Fast Food e Delivery")
# Category.create(parent_id: 2	, title: "Hambúrgueres e Sanduíches")
# Category.create(parent_id: 2	, title: "Hipermercados")
# Category.create(parent_id: 2	, title: "Importadores")
# Category.create(parent_id: 2	, title: "Lanchonete")
# Category.create(parent_id: 2	, title: "Laticínios")
# Category.create(parent_id: 2	, title: "Lojas de Conveniência")
# Category.create(parent_id: 2	, title: "Lojas de Fábrica")
# Category.create(parent_id: 2	, title: "Mercearias e Quitandas")
# Category.create(parent_id: 2	, title: "Padaria e Restaurante")
# Category.create(parent_id: 2	, title: "Padarias - Confeitarias")
# Category.create(parent_id: 2	, title: "Pastelarias")
# Category.create(parent_id: 2	, title: "Peixarias")
# Category.create(parent_id: 2	, title: "Pizza de Balcão")
# Category.create(parent_id: 2	, title: "Pizza Viagem")
# Category.create(parent_id: 2	, title: "Produtos Naturais")
# Category.create(parent_id: 2	, title: "Rotisserie")
# Category.create(parent_id: 2	, title: "Salgados")
# Category.create(parent_id: 2	, title: "Sorveterias")
# Category.create(parent_id: 2	, title: "Sucos - Sucos Naturais")
# Category.create(parent_id: 2	, title: "Supermercados")
# Category.create(parent_id: 2	, title: "Vinhos")
# Category.create(parent_id: 3	, title: "Adestradores")
# Category.create(parent_id: 3	, title: "Aquários e Peixes")
# Category.create(parent_id: 3	, title: "Avicultura")
# Category.create(parent_id: 3	, title: "Canis")
# Category.create(parent_id: 3	, title: "Clínicas e Veterinários")
# Category.create(parent_id: 3	, title: "Hotéis para Animais")
# Category.create(parent_id: 3	, title: "Pesca e Cia")
# Category.create(parent_id: 3	, title: "Pet Shop")
# Category.create(parent_id: 4	, title: "Audiovisuais")
# Category.create(parent_id: 4	, title: "Estúdios e Fotografos")
# Category.create(parent_id: 4	, title: "Fotografia - Revelacão")
# Category.create(parent_id: 4	, title: "Instrumentos Musicais")
# Category.create(parent_id: 4	, title: "Locadoras")
# Category.create(parent_id: 4	, title: "Loja - CD - DVD")
# Category.create(parent_id: 4	, title: "Loja - DJ'S")
# Category.create(parent_id: 4	, title: "Produção de vídeos")
# Category.create(parent_id: 5	, title: "Agências")
# Category.create(parent_id: 5	, title: "Alinhamento e Balanceamento")
# Category.create(parent_id: 5	, title: "Amortecedores")
# Category.create(parent_id: 5	, title: "Ar Condicionado")
# Category.create(parent_id: 5	, title: "Auto - Elétricos")
# Category.create(parent_id: 5	, title: "Auto - Peças")
# Category.create(parent_id: 5	, title: "Bancos e Capas")
# Category.create(parent_id: 5	, title: "Baterias")
# Category.create(parent_id: 5	, title: "Blindagem")
# Category.create(parent_id: 5	, title: "Borracheiros")
# Category.create(parent_id: 5	, title: "Centro de Formação de Condutores")
# Category.create(parent_id: 5	, title: "Concessionárias")
# Category.create(parent_id: 5	, title: "Conversão à Gás Natural")
# Category.create(parent_id: 5	, title: "Desmanche")
# Category.create(parent_id: 5	, title: "Despachantes")
# Category.create(parent_id: 5	, title: "Direções Hidráulicas")
# Category.create(parent_id: 5	, title: "Escapamentos")
# Category.create(parent_id: 5	, title: "Estacionamentos")
# Category.create(parent_id: 5	, title: "Funilaria e Pintura")
# Category.create(parent_id: 5	, title: "Gás Natural")
# Category.create(parent_id: 5	, title: "Importados")
# Category.create(parent_id: 5	, title: "Lava Rápido")
# Category.create(parent_id: 5	, title: "Locadora")
# Category.create(parent_id: 5	, title: "Martelinho de Ouro")
# Category.create(parent_id: 5	, title: "Motocicletas")
# Category.create(parent_id: 5	, title: "Oficinas Mecânicas")
# Category.create(parent_id: 5	, title: "Peças Recondicionadas")
# Category.create(parent_id: 5	, title: "Pneus")
# Category.create(parent_id: 5	, title: "Postos de Combustível")
# Category.create(parent_id: 5	, title: "Radiadores")
# Category.create(parent_id: 5	, title: "Rodas")
# Category.create(parent_id: 5	, title: "Seguros")
# Category.create(parent_id: 5	, title: "Serviço de Suspensão")
# Category.create(parent_id: 5	, title: "Som e Acessórios")
# Category.create(parent_id: 5	, title: "Tapeçaria")
# Category.create(parent_id: 5	, title: "Velocímetros")
# Category.create(parent_id: 5	, title: "Vidros")
# Category.create(parent_id: 6	, title: "Botecos")
# Category.create(parent_id: 6	, title: "Cachaçaria")
# Category.create(parent_id: 6	, title: "Chopp e Cerveja")
# Category.create(parent_id: 6	, title: "Cigar Bar")
# Category.create(parent_id: 6	, title: "Em Hotel")
# Category.create(parent_id: 6	, title: "Espetinhos")
# Category.create(parent_id: 6	, title: "Fim de Noite")
# Category.create(parent_id: 6	, title: "Galeteria")
# Category.create(parent_id: 6	, title: "GLS")
# Category.create(parent_id: 6	, title: "Happy Hour")
# Category.create(parent_id: 6	, title: "Mexicano")
# Category.create(parent_id: 6	, title: "Música ao Vivo")
# Category.create(parent_id: 6	, title: "Paquera")
# Category.create(parent_id: 6	, title: "Para Dançar")
# Category.create(parent_id: 6	, title: "Para ir a Dois")
# Category.create(parent_id: 6	, title: "Pizza Bar")
# Category.create(parent_id: 6	, title: "Pubs")
# Category.create(parent_id: 6	, title: "Sanduíches")
# Category.create(parent_id: 6	, title: "Variados")
# Category.create(parent_id: 7	, title: "Aquecedores")
# Category.create(parent_id: 7	, title: "Ar Condicionado")
# Category.create(parent_id: 7	, title: "Armários de Cozinha")
# Category.create(parent_id: 7	, title: "Arquitetura e Decoração")
# Category.create(parent_id: 7	, title: "Assoalhos")
# Category.create(parent_id: 7	, title: "Banheiras")
# Category.create(parent_id: 7	, title: "Cama, Mesa e Banho")
# Category.create(parent_id: 7	, title: "Carpetes e Cortinas")
# Category.create(parent_id: 7	, title: "Colchões - Travesseiros")
# Category.create(parent_id: 7	, title: "Decoração")
# Category.create(parent_id: 7	, title: "Divisórias")
# Category.create(parent_id: 7	, title: "Espelhos - Quadros")
# Category.create(parent_id: 7	, title: "Estofados")
# Category.create(parent_id: 7	, title: "Gesso")
# Category.create(parent_id: 7	, title: "Lustres - Luminárias")
# Category.create(parent_id: 7	, title: "Móveis")
# Category.create(parent_id: 7	, title: "Móveis Planejados")
# Category.create(parent_id: 7	, title: "Móveis Rústicos")
# Category.create(parent_id: 7	, title: "Papeis de Parede")
# Category.create(parent_id: 7	, title: "Plantas - Paisagismo")
# Category.create(parent_id: 7	, title: "Portas e Portões")
# Category.create(parent_id: 7	, title: "Produtos de Limpeza")
# Category.create(parent_id: 7	, title: "Redes de proteção")
# Category.create(parent_id: 7	, title: "Tapetes")
# Category.create(parent_id: 7	, title: "Tintas e Texturas")
# Category.create(parent_id: 8	, title: "Andaimes")
# Category.create(parent_id: 8	, title: "Calhas")
# Category.create(parent_id: 8	, title: "Churrasqueiras")
# Category.create(parent_id: 8	, title: "Construtoras")
# Category.create(parent_id: 8	, title: "Escadas")
# Category.create(parent_id: 8	, title: "Estruturas para Construções")
# Category.create(parent_id: 8	, title: "Fechaduras e Ferragens")
# Category.create(parent_id: 8	, title: "Ferramentas")
# Category.create(parent_id: 8	, title: "Forros")
# Category.create(parent_id: 8	, title: "Instalações Elétricas")
# Category.create(parent_id: 8	, title: "Instalações Hidráulicas")
# Category.create(parent_id: 8	, title: "Madeiras")
# Category.create(parent_id: 8	, title: "Marcenarias")
# Category.create(parent_id: 8	, title: "Mármores e Granitos")
# Category.create(parent_id: 8	, title: "Materiais Construção")
# Category.create(parent_id: 8	, title: "Materiais Elétricos")
# Category.create(parent_id: 8	, title: "Piscinas")
# Category.create(parent_id: 8	, title: "Pisos e Azulejos")
# Category.create(parent_id: 8	, title: "Serralheria")
# Category.create(parent_id: 8	, title: "Telhas")
# Category.create(parent_id: 8	, title: "Vidraçarias")
# Category.create(parent_id: 9	, title: "Advogados")
# Category.create(parent_id: 9	, title: "Arquitetos")
# Category.create(parent_id: 9	, title: "Contadores")
# Category.create(parent_id: 9	, title: "Corretores")
# Category.create(parent_id: 9	, title: "Decoradores")
# Category.create(parent_id: 9	, title: "Dentistas")
# Category.create(parent_id: 9	, title: "Despachantes")
# Category.create(parent_id: 9	, title: "Detetives")
# Category.create(parent_id: 9	, title: "Eletricistas")
# Category.create(parent_id: 9	, title: "Enfermeiros")
# Category.create(parent_id: 9	, title: "Engenheiros")
# Category.create(parent_id: 9	, title: "Fisioterapeutas")
# Category.create(parent_id: 9	, title: "Fonoaudiólogos")
# Category.create(parent_id: 9	, title: "Fotógrafos")
# Category.create(parent_id: 9	, title: "Informática")
# Category.create(parent_id: 9	, title: "Médicos")
# Category.create(parent_id: 9	, title: "Nutricionistas")
# Category.create(parent_id: 9	, title: "Peritos")
# Category.create(parent_id: 9	, title: "Professores")
# Category.create(parent_id: 9	, title: "Programadores")
# Category.create(parent_id: 9	, title: "Psicólogos")
# Category.create(parent_id: 9	, title: "Técnicos")
# Category.create(parent_id: 9	, title: "Tradutores")
# Category.create(parent_id: 9	, title: "Turismo")
# Category.create(parent_id: 10	, title: "Aulas Particulares")
# Category.create(parent_id: 10	, title: "Berçários")
# Category.create(parent_id: 10	, title: "Colégios Particulares")
# Category.create(parent_id: 10	, title: "Creches")
# Category.create(parent_id: 10	, title: "Cursinhos Preparatórios")
# Category.create(parent_id: 10	, title: "Curso de Informática")
# Category.create(parent_id: 10	, title: "Cursos de Corte e Costura")
# Category.create(parent_id: 10	, title: "Cursos de Culinária")
# Category.create(parent_id: 10	, title: "Cursos de Desenho")
# Category.create(parent_id: 10	, title: "Cursos de Enfermagem")
# Category.create(parent_id: 10	, title: "Cursos de Idiomas")
# Category.create(parent_id: 10	, title: "Cursos de Pintura")
# Category.create(parent_id: 10	, title: "Cursos Pré-Vestibulares")
# Category.create(parent_id: 10	, title: "Cursos Profissionalizantes")
# Category.create(parent_id: 10	, title: "Escola Infantis")
# Category.create(parent_id: 10	, title: "Escolas de Arte")
# Category.create(parent_id: 10	, title: "Escolas de Cabeleireiros")
# Category.create(parent_id: 10	, title: "Escolas de Dança")
# Category.create(parent_id: 10	, title: "Escolas de Estética")
# Category.create(parent_id: 10	, title: "Escolas de Música")
# Category.create(parent_id: 10	, title: "Escolas para Excepcionais")
# Category.create(parent_id: 10	, title: "Escolas Técnicas")
# Category.create(parent_id: 10	, title: "Faculdades e Universidades")
# Category.create(parent_id: 10	, title: "Intercâmbio")
# Category.create(parent_id: 11	, title: "Acessórios para celular")
# Category.create(parent_id: 11	, title: "Antenas")
# Category.create(parent_id: 11	, title: "Aparelhos Eletrônicos")
# Category.create(parent_id: 11	, title: "Audio e Video")
# Category.create(parent_id: 11	, title: "Eletrodomésticos")
# Category.create(parent_id: 11	, title: "Iluminação")
# Category.create(parent_id: 11	, title: "Peças e Componentes")
# Category.create(parent_id: 11	, title: "Rede de Lojas")
# Category.create(parent_id: 12	, title: "Animações")
# Category.create(parent_id: 12	, title: "Artigos para Festas")
# Category.create(parent_id: 12	, title: "Bandas")
# Category.create(parent_id: 12	, title: "Buffet")
# Category.create(parent_id: 12	, title: "Buffet em Domicílio")
# Category.create(parent_id: 12	, title: "Buffet Infantil")
# Category.create(parent_id: 12	, title: "Convites e Lembranças")
# Category.create(parent_id: 12	, title: "Decoração")
# Category.create(parent_id: 12	, title: "Fantasias")
# Category.create(parent_id: 12	, title: "Fogos de Artifício")
# Category.create(parent_id: 12	, title: "Locação de Brinquedos")
# Category.create(parent_id: 12	, title: "Locação de Mesas e Cadeiras")
# Category.create(parent_id: 12	, title: "Organização - Promoção")
# Category.create(parent_id: 12	, title: "Salões")
# Category.create(parent_id: 12	, title: "Som e Iluminação")
# Category.create(parent_id: 13	, title: "Alemães")
# Category.create(parent_id: 13	, title: "Árabes")
# Category.create(parent_id: 13	, title: "Argentinos")
# Category.create(parent_id: 13	, title: "Armênio")
# Category.create(parent_id: 13	, title: "Asiáticos")
# Category.create(parent_id: 13	, title: "Brasileiros")
# Category.create(parent_id: 13	, title: "Carnes e Rodízios")
# Category.create(parent_id: 13	, title: "Chineses")
# Category.create(parent_id: 13	, title: "Coreanos")
# Category.create(parent_id: 13	, title: "Cozinha Contemporânea")
# Category.create(parent_id: 13	, title: "Cozinha Rápida")
# Category.create(parent_id: 13	, title: "Escandinavo")
# Category.create(parent_id: 13	, title: "Espanhóis")
# Category.create(parent_id: 13	, title: "Franceses")
# Category.create(parent_id: 13	, title: "Grego")
# Category.create(parent_id: 13	, title: "Indianos")
# Category.create(parent_id: 13	, title: "Italianos")
# Category.create(parent_id: 13	, title: "Japoneses")
# Category.create(parent_id: 13	, title: "Judaicos")
# Category.create(parent_id: 13	, title: "Marroquinos")
# Category.create(parent_id: 13	, title: "Mediterrâneos")
# Category.create(parent_id: 13	, title: "Mexicano")
# Category.create(parent_id: 13	, title: "Naturais")
# Category.create(parent_id: 13	, title: "Peixes e Frutos do Mar")
# Category.create(parent_id: 13	, title: "Pizzaria")
# Category.create(parent_id: 13	, title: "Portugueses")
# Category.create(parent_id: 13	, title: "Sérvio")
# Category.create(parent_id: 13	, title: "Suíços")
# Category.create(parent_id: 13	, title: "Tailandês")
# Category.create(parent_id: 13	, title: "Variados")
# Category.create(parent_id: 14	, title: "Apart hotél")
# Category.create(parent_id: 14	, title: "Hospedarias")
# Category.create(parent_id: 14	, title: "Hotéis")
# Category.create(parent_id: 14	, title: "Motéis")
# Category.create(parent_id: 14	, title: "Pensionatos")
# Category.create(parent_id: 14	, title: "Pensões")
# Category.create(parent_id: 14	, title: "Pousadas")
# Category.create(parent_id: 16	, title: "Assistência e Manutenção")
# Category.create(parent_id: 16	, title: "Comércio e Serviços")
# Category.create(parent_id: 16	, title: "Comércio Eletrônico")
# Category.create(parent_id: 16	, title: "Cursos e Treinamentos")
# Category.create(parent_id: 16	, title: "Desenvolvimento Web")
# Category.create(parent_id: 16	, title: "Fabricantes")
# Category.create(parent_id: 16	, title: "LanHouse")
# Category.create(parent_id: 16	, title: "Notebook")
# Category.create(parent_id: 16	, title: "Softwares | Sistemas")
# Category.create(parent_id: 16	, title: "Suporte Técnico")
# Category.create(parent_id: 16	, title: "Suprimentos")
# Category.create(parent_id: 17	, title: "Atacadista")
# Category.create(parent_id: 17	, title: "Bazar")
# Category.create(parent_id: 17	, title: "Caixas para Presentes")
# Category.create(parent_id: 17	, title: "Carimbos")
# Category.create(parent_id: 17	, title: "Copiadora")
# Category.create(parent_id: 17	, title: "Editora")
# Category.create(parent_id: 17	, title: "Gráficas")
# Category.create(parent_id: 17	, title: "Livrarias")
# Category.create(parent_id: 17	, title: "Materiais Escolares")
# Category.create(parent_id: 17	, title: "Papelarias")
# Category.create(parent_id: 17	, title: "Sebo")
# Category.create(parent_id: 18	, title: "Acupuntura")
# Category.create(parent_id: 18	, title: "Ambulâncias")
# Category.create(parent_id: 18	, title: "Aparelhos Ortopédicos")
# Category.create(parent_id: 18	, title: "Aparelhos para Surdez")
# Category.create(parent_id: 18	, title: "Atendimento Domiciliar")
# Category.create(parent_id: 18	, title: "Cadeiras de Rodas")
# Category.create(parent_id: 18	, title: "Casas de Saúde")
# Category.create(parent_id: 18	, title: "Clínica de Fraturas")
# Category.create(parent_id: 18	, title: "Clínica de Reabilitação")
# Category.create(parent_id: 18	, title: "Clínicas")
# Category.create(parent_id: 18	, title: "Clínicas Odontológicas")
# Category.create(parent_id: 18	, title: "Consultórios")
# Category.create(parent_id: 18	, title: "Dentistas")
# Category.create(parent_id: 18	, title: "Equipamentos Odontológicos")
# Category.create(parent_id: 18	, title: "Esteticistas")
# Category.create(parent_id: 18	, title: "Farmácias de Manipulação")
# Category.create(parent_id: 18	, title: "Farmácias e Drogarias")
# Category.create(parent_id: 18	, title: "Farmácias Homeopáticas")
# Category.create(parent_id: 18	, title: "Fisioterapia")
# Category.create(parent_id: 18	, title: "Fonoaudiologia")
# Category.create(parent_id: 18	, title: "Homeopatia")
# Category.create(parent_id: 18	, title: "Hospitais Particulares")
# Category.create(parent_id: 18	, title: "Naturologia")
# Category.create(parent_id: 18	, title: "Neurologia")
# Category.create(parent_id: 18	, title: "Nutricionista")
# Category.create(parent_id: 18	, title: "Ortopedia")
# Category.create(parent_id: 18	, title: "Óticas")
# Category.create(parent_id: 18	, title: "Otorrinolaringologia")
# Category.create(parent_id: 18	, title: "Planos de Saúde")
# Category.create(parent_id: 18	, title: "Produtos Naturais")
# Category.create(parent_id: 18	, title: "Produtos para Alérgicos")
# Category.create(parent_id: 18	, title: "Próteses")
# Category.create(parent_id: 18	, title: "Psicanalistas")
# Category.create(parent_id: 18	, title: "Psicólogos")
# Category.create(parent_id: 18	, title: "Terapias Alternativas")
# Category.create(parent_id: 18	, title: "Urologia")
# Category.create(parent_id: 19	, title: "Agências de Modelos")
# Category.create(parent_id: 19	, title: "Alfaiates")
# Category.create(parent_id: 19	, title: "Aluguel de Roupas")
# Category.create(parent_id: 19	, title: "Armarinhos")
# Category.create(parent_id: 19	, title: "Aviamentos")
# Category.create(parent_id: 19	, title: "Bijuterias")
# Category.create(parent_id: 19	, title: "Bolsas")
# Category.create(parent_id: 19	, title: "Bronzeamento artificial")
# Category.create(parent_id: 19	, title: "Cabeleireiros")
# Category.create(parent_id: 19	, title: "Calçados")
# Category.create(parent_id: 19	, title: "Clínicas de Estéticas")
# Category.create(parent_id: 19	, title: "Confecções")
# Category.create(parent_id: 19	, title: "Corte e Costura")
# Category.create(parent_id: 19	, title: "Cosméticos")
# Category.create(parent_id: 19	, title: "Costureira")
# Category.create(parent_id: 19	, title: "Couro")
# Category.create(parent_id: 19	, title: "Depilação")
# Category.create(parent_id: 19	, title: "Infantil")
# Category.create(parent_id: 19	, title: "Institutos de Beleza")
# Category.create(parent_id: 19	, title: "Joalherias")
# Category.create(parent_id: 19	, title: "Lingeries")
# Category.create(parent_id: 19	, title: "Malharia")
# Category.create(parent_id: 19	, title: "Moda Feminina")
# Category.create(parent_id: 19	, title: "Moda Infantil")
# Category.create(parent_id: 19	, title: "Moda Masculina")
# Category.create(parent_id: 19	, title: "Moda Unissex")
# Category.create(parent_id: 19	, title: "Noivas")
# Category.create(parent_id: 19	, title: "Outlet")
# Category.create(parent_id: 19	, title: "Perfumarias")
# Category.create(parent_id: 19	, title: "Perucas")
# Category.create(parent_id: 19	, title: "Podólogo")
# Category.create(parent_id: 19	, title: "Salão de Beleza")
# Category.create(parent_id: 19	, title: "Sapateiros")
# Category.create(parent_id: 19	, title: "Sportware-Fitness-Praia")
# Category.create(parent_id: 19	, title: "Tatuagens")
# Category.create(parent_id: 19	, title: "Tecidos")
# Category.create(parent_id: 20	, title: "Artesanatos")
# Category.create(parent_id: 20	, title: "Artigos Evangélicos")
# Category.create(parent_id: 20	, title: "Floriculturas")
# Category.create(parent_id: 20	, title: "Joalherias")
# Category.create(parent_id: 20	, title: "Perfumaria")
# Category.create(parent_id: 20	, title: "Pratarias")
# Category.create(parent_id: 20	, title: "Relojoaria")
# Category.create(parent_id: 20	, title: "Telemensagens")
# Category.create(parent_id: 20	, title: "Variados")
# Category.create(parent_id: 21	, title: "Agências de Empregos")
# Category.create(parent_id: 21	, title: "Água Mineral")
# Category.create(parent_id: 21	, title: "Alarme e Monitoramento")
# Category.create(parent_id: 21	, title: "Assistência Técnica")
# Category.create(parent_id: 21	, title: "Cargas e Encomendas")
# Category.create(parent_id: 21	, title: "Chaveiros")
# Category.create(parent_id: 21	, title: "Corretora de Seguros")
# Category.create(parent_id: 21	, title: "Dedetização")
# Category.create(parent_id: 21	, title: "Desentupidora")
# Category.create(parent_id: 21	, title: "Distribuidor de Gás")
# Category.create(parent_id: 21	, title: "Entregas Rápidas")
# Category.create(parent_id: 21	, title: "Faixas Letreiros")
# Category.create(parent_id: 21	, title: "Gráfica")
# Category.create(parent_id: 21	, title: "Importação e Exportação")
# Category.create(parent_id: 21	, title: "Lavanderias")
# Category.create(parent_id: 21	, title: "Limpeza de Carpetes")
# Category.create(parent_id: 21	, title: "Mensagens Fonadas")
# Category.create(parent_id: 21	, title: "Motorista e Manobrista")
# Category.create(parent_id: 21	, title: "Mudanças")
# Category.create(parent_id: 21	, title: "Taxi")
# Category.create(parent_id: 22	, title: "Agências")
# Category.create(parent_id: 22	, title: "Brindes")
# Category.create(parent_id: 22	, title: "Comunicação Visual")
# Category.create(parent_id: 22	, title: "Editoras")
# Category.create(parent_id: 22	, title: "Propaganda")
# Category.create(parent_id: 23	, title: "Agência de Viagens")
# Category.create(parent_id: 23	, title: "Agências de Turismo")
# Category.create(parent_id: 23	, title: "Transporte Rodoviário")



# City.create(id: 1  ,name: "ADRIANÓPOLIS".mb_chars.titlecase.to_s)
# City.create(id: 2 ,name: "AGUDOS DO SUL".mb_chars.titlecase.to_s)
# City.create(id: 3 ,name: "ALMIRANTE TAMANDARÉ".mb_chars.titlecase.to_s)
# City.create(id: 4  ,name: "ANTONINA".mb_chars.titlecase.to_s)
# City.create(id: 5  ,name: "ARAUCÁRIA".mb_chars.titlecase.to_s)
# City.create(id: 6  ,name: "BALSA NOVA".mb_chars.titlecase.to_s)
# City.create(id: 7  ,name: "BOCAIUVA DO SUL".mb_chars.titlecase.to_s)
# City.create(id: 8  ,name: "CAMPINA GRANDE DO SUL".mb_chars.titlecase.to_s)
# City.create(id: 9  ,name: "CAMPO DO TENENTE".mb_chars.titlecase.to_s)
# City.create(id: 10  ,name: "CAMPO LARGO".mb_chars.titlecase.to_s)
# City.create(id: 11  ,name: "CAMPO MAGRO".mb_chars.titlecase.to_s)
# City.create(id: 12  ,name: "CERRO AZUL".mb_chars.titlecase.to_s)
# City.create(id: 13  ,name: "COLOMBO".mb_chars.titlecase.to_s)
# City.create(id: 14  ,name: "CONTENDA".mb_chars.titlecase.to_s)
# City.create(id: 15  ,name: "CURITIBA".mb_chars.titlecase.to_s)
# City.create(id: 16  ,name: "DOUTOR ULYSSES".mb_chars.titlecase.to_s)
# City.create(id: 17  ,name: "FAZENDA RIO GRANDE".mb_chars.titlecase.to_s)
# City.create(id: 18  ,name: "GUARAQUEÇABA".mb_chars.titlecase.to_s)
# City.create(id: 19  ,name: "GUARATUBA".mb_chars.titlecase.to_s)
# City.create(id: 20  ,name: "ITAPERUÇU".mb_chars.titlecase.to_s)
# City.create(id: 21  ,name: "LAPA".mb_chars.titlecase.to_s)
# City.create(id: 22  ,name: "MANDIRITUBA".mb_chars.titlecase.to_s)
# City.create(id: 23  ,name: "MATINHOS".mb_chars.titlecase.to_s)
# City.create(id: 24  ,name: "MORRETES".mb_chars.titlecase.to_s)
# City.create(id: 25  ,name: "PARANAGUÁ".mb_chars.titlecase.to_s)
# City.create(id: 26  ,name: "PIEN".mb_chars.titlecase.to_s)
# City.create(id: 27  ,name: "PINHAIS".mb_chars.titlecase.to_s)
# City.create(id: 28  ,name: "PIRAQUARA".mb_chars.titlecase.to_s)
# City.create(id: 29  ,name: "PONTAL DO PARANÁ".mb_chars.titlecase.to_s)
# City.create(id: 30  ,name: "QUATRO BARRAS".mb_chars.titlecase.to_s)
# City.create(id: 31  ,name: "QUITANDINHA".mb_chars.titlecase.to_s)
# City.create(id: 32  ,name: "RIO BRANCO DO SUL".mb_chars.titlecase.to_s)
# City.create(id: 33  ,name: "RIO NEGRO".mb_chars.titlecase.to_s)
# City.create(id: 34  ,name: "SÃO JOSÉ DOS PINHAIS".mb_chars.titlecase.to_s)
# City.create(id: 35  ,name: "TIJUCAS DO SUL".mb_chars.titlecase.to_s)
# City.create(id: 36  ,name: "TUNAS DO PARANÁ".mb_chars.titlecase.to_s)

# Neighborhood.create(city_id: 15,name: "Abranches")
# Neighborhood.create(city_id: 15,name: "Água Verde")
# Neighborhood.create(city_id: 15,name: "Ahú")
# Neighborhood.create(city_id: 15,name: "Alto Boqueirão")
# Neighborhood.create(city_id: 15,name: "Alto da Glória")
# Neighborhood.create(city_id: 15,name: "Alto da XV")
# Neighborhood.create(city_id: 15,name: "Atuba")
# Neighborhood.create(city_id: 15,name: "Augusta")
# Neighborhood.create(city_id: 15,name: "Bacacheri")
# Neighborhood.create(city_id: 15,name: "Bairro Alto")
# Neighborhood.create(city_id: 15,name: "Barreirinha")
# Neighborhood.create(city_id: 15,name: "Batel")
# Neighborhood.create(city_id: 15,name: "Boa Vista")
# Neighborhood.create(city_id: 15,name: "Bom Retiro")
# Neighborhood.create(city_id: 15,name: "Boqueirão")
# Neighborhood.create(city_id: 15,name: "Butiatuvinha")
# Neighborhood.create(city_id: 15,name: "Cabral")
# Neighborhood.create(city_id: 15,name: "Cachoeira")
# Neighborhood.create(city_id: 15,name: "Cajuru")
# Neighborhood.create(city_id: 15,name: "Campina do Siqueira")
# Neighborhood.create(city_id: 15,name: "Campo Comprido")
# Neighborhood.create(city_id: 15,name: "Campo de Santana")
# Neighborhood.create(city_id: 15,name: "Capão da Imbuia")
# Neighborhood.create(city_id: 15,name: "Capão Raso")
# Neighborhood.create(city_id: 15,name: "Cascatinha")
# Neighborhood.create(city_id: 15,name: "Centro")
# Neighborhood.create(city_id: 15,name: "Centro Histórico")
# Neighborhood.create(city_id: 15,name: "Caximba")
# Neighborhood.create(city_id: 15,name: "Centro Cívico")
# Neighborhood.create(city_id: 15,name: "Champagnat")
# Neighborhood.create(city_id: 15,name: "Cidade Industrial")
# Neighborhood.create(city_id: 15,name: "Cristo Rei")
# Neighborhood.create(city_id: 15,name: "Fanny")
# Neighborhood.create(city_id: 15,name: "Fazendinha")
# Neighborhood.create(city_id: 15,name: "Ganchinho")
# Neighborhood.create(city_id: 15,name: "Guabirotuba")
# Neighborhood.create(city_id: 15,name: "Guaíra")
# Neighborhood.create(city_id: 15,name: "Hauer")
# Neighborhood.create(city_id: 15,name: "Hugo Lange")
# Neighborhood.create(city_id: 15,name: "Jardim Botânico")
# Neighborhood.create(city_id: 15,name: "Jardim Social")
# Neighborhood.create(city_id: 15,name: "Jardim das Américas")
# Neighborhood.create(city_id: 15,name: "Juvevê")
# Neighborhood.create(city_id: 15,name: "Lamenha Pequena")
# Neighborhood.create(city_id: 15,name: "Lindóia")
# Neighborhood.create(city_id: 15,name: "Mercês")
# Neighborhood.create(city_id: 15,name: "Mossunguê (Ecoville)")
# Neighborhood.create(city_id: 15,name: "Novo Mundo")
# Neighborhood.create(city_id: 15,name: "Orleans")
# Neighborhood.create(city_id: 15,name: "Parolin")
# Neighborhood.create(city_id: 15,name: "Pilarzinho")
# Neighborhood.create(city_id: 15,name: "Pinheirinho")
# Neighborhood.create(city_id: 15,name: "Portão")
# Neighborhood.create(city_id: 15,name: "Prado Velho")
# Neighborhood.create(city_id: 15,name: "Rebouças")
# Neighborhood.create(city_id: 15,name: "Riviera")
# Neighborhood.create(city_id: 15,name: "Santa Cândida")
# Neighborhood.create(city_id: 15,name: "Santa Felicidade")
# Neighborhood.create(city_id: 15,name: "Santa Quitéria")
# Neighborhood.create(city_id: 15,name: "Santo Inácio")
# Neighborhood.create(city_id: 15,name: "São Braz")
# Neighborhood.create(city_id: 15,name: "São Francisco")
# Neighborhood.create(city_id: 15,name: "São João")
# Neighborhood.create(city_id: 15,name: "São Lourenço")
# Neighborhood.create(city_id: 15,name: "São Miguel")
# Neighborhood.create(city_id: 15,name: "Seminário")
# Neighborhood.create(city_id: 15,name: "Sítio Cercado")
# Neighborhood.create(city_id: 15,name: "Taboão")
# Neighborhood.create(city_id: 15,name: "Tarumã")
# Neighborhood.create(city_id: 15,name: "Tatuquara")
# Neighborhood.create(city_id: 15,name: "Tingui")
# Neighborhood.create(city_id: 15,name: "Uberaba")
# Neighborhood.create(city_id: 15,name: "Umbará")
# Neighborhood.create(city_id: 15,name: "Vila Izabel")
# Neighborhood.create(city_id: 15,name: "Vista Alegre")
# Neighborhood.create(city_id: 15,name: "Xaxim")


nao_identificados = 0
identificados = 0

File.open("db/restaurantes.yml", 'r') do |file|
	arquivo = YAML::load(file)
 	bar = ProgressBar.new(arquivo.count)
	arquivo.each do |record|
		search = Neighborhood.search("#{record['bairro']}")
 		bairro = search.first
		#puts "#{record['nome'].mb_chars.titlecase.to_s} #{record['endereco'].mb_chars.titlecase.to_s}"
		if bairro
			#puts "#{record['idanuncio']} - BAIRRO ([#{record['bairro']}:#{bairro.name}][#{bairro.id}])"
			identificados += 1
			Place.create(
				neighborhood_id: bairro.id,
				city_id: 15,
				state: "PR",
				title: record['nome'].mb_chars.titlecase.to_s,
				address: record['endereco'].mb_chars.titlecase.to_s,
				number: record['numero'],
				cep: record['cep'],
				category_ids: [ 13, record['idsubdepartamento'] ],
				phone: record['telefones']
			)
		else
			nao_identificados += 1
			puts "#{record['idanuncio']} - BAIRRO (#{record['bairro']}) = NÃO IDENFICADO | CIDADE (#{record['cidade']})"
		end
		bar.increment!
	end

	puts "Migrados #{identificados}"
	puts "Nao Migrados #{nao_identificados}"
end

# File.open("db/restaurantes.yml", 'r') do |file|
# 	arquivo = YAML::load(file)
# 	bar = ProgressBar.new(arquivo.count)
# 	arquivo.each do |record|
# 		search = Neighborhood.search("#{record['bairro']}", order: {title: :asc} )
# 		bairro = search.first
# 		Place.create(
# 			neighborhood_id: bairro.id,
# 			city_id: "1",
# 			state: "PR",
# 			parent_ids: [1],
# 			title: record['nome'].mb_chars.titlecase.to_s,
# 			address: record['endereco'].mb_chars.titlecase.to_s,
# 			number: record['numero'],
# 			cep: record['cep']
# 		)
# 		bar.increment!
# 	end
# end

# 100 restaurantes
=begin

20.times do
	Place.create(
	title: Faker::Company.name,
	address: Faker::Address.street_name,
	neighborhood_id: 2,
	number: Faker::Address.building_number,
	city_id: "1",
	state: "PR",
	cep: Faker::Address.zip_code,
	parent_ids: [1, rand(5)+1])
end

20.times do
	Place.create(
	title: Faker::Company.name,
	address: Faker::Address.street_name,
	neighborhood_id: 2,
	number: Faker::Address.building_number,
	city_id: "1",
	state: "PR",
	cep: Faker::Address.zip_code,
	parent_ids: [6])
end
=end


# 100.times do
# 	Place.create(
# 	title: Faker::Company.name,
# 	address: Faker::Address.street_name,
# 	neighborhood_id: "1",
# 	number: Faker::Address.building_number,
# 	city_id: "1",
# 	state: "PR",
# 	cep: Faker::Address.zip_code,
# 	parent_ids: [Category.last])
# end

